<?php

namespace App\Http\Resources\V1\Abstracts\System\Branch;

use App\Enums\Platform;
use App\Http\Resources\PlatformResource;
use Illuminate\Http\Request;

abstract class BranchAbstractResource extends PlatformResource
{
    // Concrete implementations (Web/Mobile) will implement platform() method
    // and define their own toArray() method
    public function toArray(Request $request)
    {
        return [
            'id' => 'general'
        ]; // TODO: Change the autogenerated stub
    }
}
